'use strict';

const REPO = 'msplserviceacc/msp-web-dev-feed';
const FILE_PATH = 'public/weeks-data.js';

const PROMPT = (weekKey) => `You are generating a weekly web development intelligence brief for MSP Launchpad, a web agency specialising in Webflow, Figma, n8n automation, and client website delivery.

Generate exactly 8 intelligence items for the week of ${weekKey}. Items should cover real, current trends in web development tools, performance standards, AI tooling, Webflow updates, CSS advances, and agency-relevant SaaS changes.

Respond with ONLY a valid JSON array (no markdown, no explanation) with exactly this structure for each item:
[
  {
    "title": "Short punchy headline",
    "tier": "s",
    "tierLabel": "S Tier",
    "pipeline": "Relevant pipeline stage e.g. QA → Performance",
    "source": "Source name",
    "url": "https://relevant-source-url.com",
    "benefit": "One sentence: what this saves, earns, or protects for the agency — not developer outcomes",
    "roi": "Immediate",
    "fit": 5,
    "why": "2-3 sentences explaining why this matters for MSP Launchpad specifically",
    "steps": ["Concrete step 1", "Concrete step 2", "Concrete step 3"],
    "impl": {"Research": "1h", "Build": "2h", "QA": "1h", "Rollout": "1h", "Total": "5h"},
    "impact": {
      "Build Speed": {"val": "+10%"},
      "QA Pass Rate": {"val": "+5%"},
      "Page Perf": {"val": "—", "neutral": true}
    },
    "compat": {
      "Webflow": "Yes",
      "Figma": "No",
      "n8n": "Partial",
      "Cloudflare": "Yes",
      "Playwright": "Yes",
      "Website QA": "Yes"
    }
  }
]

Use tier: s for immediate action required (1-2 items), a for adopt soon (2-3 items), b for worth knowing (2-3 items), c for watch list (1 item).
roi values: "Immediate", "High", "Medium", "Watch"
fit: 1-5 integer
compat values for each tool: "Yes", "Partial", or "No"
For impl, use "—" for stages that don't apply.`;

module.exports = async (req, res) => {
  if (req.headers.authorization !== `Bearer ${process.env.CRON_SECRET}`) {
    return res.status(401).json({ error: 'Unauthorized' });
  }

  const githubToken = process.env.GITHUB_TOKEN;
  const anthropicKey = process.env.ANTHROPIC_API_KEY;

  if (!githubToken) return res.status(500).json({ error: 'GITHUB_TOKEN not set' });
  if (!anthropicKey) return res.status(500).json({ error: 'ANTHROPIC_API_KEY not set' });

  try {
    // Compute this week's Monday
    const today = new Date();
    const day = today.getDay();
    const diff = day === 0 ? 6 : day - 1;
    const monday = new Date(today);
    monday.setDate(today.getDate() - diff);
    monday.setHours(12, 0, 0, 0);
    const weekKey = monday.toISOString().split('T')[0];

    // Fetch current weeks-data.js from GitHub
    const ghRes = await fetch(`https://api.github.com/repos/${REPO}/contents/${FILE_PATH}`, {
      headers: {
        Authorization: `Bearer ${githubToken}`,
        Accept: 'application/vnd.github+json',
        'X-GitHub-Api-Version': '2022-11-28'
      }
    });
    if (!ghRes.ok) throw new Error(`GitHub fetch failed: ${ghRes.status}`);
    const ghData = await ghRes.json();
    const currentContent = Buffer.from(ghData.content, 'base64').toString('utf8');
    const fileSha = ghData.sha;

    // Skip if already generated this week
    if (currentContent.includes(`'${weekKey}'`)) {
      return res.json({ message: 'Already generated', week: weekKey });
    }

    // Call Claude API
    const aiRes = await fetch('https://api.anthropic.com/v1/messages', {
      method: 'POST',
      headers: {
        'x-api-key': anthropicKey,
        'anthropic-version': '2023-06-01',
        'content-type': 'application/json'
      },
      body: JSON.stringify({
        model: 'claude-sonnet-4-6',
        max_tokens: 8000,
        messages: [{ role: 'user', content: PROMPT(weekKey) }]
      })
    });
    if (!aiRes.ok) throw new Error(`Anthropic error: ${await aiRes.text()}`);

    const aiData = await aiRes.json();
    const text = aiData.content[0].text.trim();

    const jsonMatch = text.match(/\[[\s\S]*\]/);
    if (!jsonMatch) throw new Error('Could not parse AI response as JSON array');
    const items = JSON.parse(jsonMatch[0]);
    if (!Array.isArray(items) || items.length === 0) throw new Error('Invalid items array');

    // Inject new week at top of WEEKS object
    const newEntry = `  '${weekKey}': ${JSON.stringify(items)},\n`;
    const updatedContent = currentContent.replace(/^var WEEKS = \{/m, `var WEEKS = {\n${newEntry}`);

    // Commit updated file to GitHub — Vercel auto-deploys from this push
    const commitRes = await fetch(`https://api.github.com/repos/${REPO}/contents/${FILE_PATH}`, {
      method: 'PUT',
      headers: {
        Authorization: `Bearer ${githubToken}`,
        Accept: 'application/vnd.github+json',
        'X-GitHub-Api-Version': '2022-11-28',
        'Content-Type': 'application/json'
      },
      body: JSON.stringify({
        message: `Add week ${weekKey} — auto-generated by Claude`,
        content: Buffer.from(updatedContent, 'utf8').toString('base64'),
        sha: fileSha,
        committer: { name: 'MSP Launchpad Bot', email: 'bot@msplaunchpad.com' }
      })
    });
    if (!commitRes.ok) throw new Error(`GitHub commit failed: ${await commitRes.text()}`);

    return res.json({ success: true, week: weekKey, items: items.length });

  } catch (err) {
    console.error('Generate error:', err);
    return res.status(500).json({ error: err.message });
  }
};
